spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  redis:
    host: 139.159.232.117
    port: 6379
    password: 123456
  data:
    cassandra:
      keyspace-name: scbase
      contact-points: 139.159.232.117
      port: 9042
      local-datacenter: datacenter1
      username: cassandra
      password: cassandra
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://139.159.232.117:3306/sharechat?useUnicode=true&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  neo4j:
    uri: neo4j://139.159.232.117:7687
    authentication:
      username: neo4j
      password: ecnu542_
server:
  port: 8888
aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyid: LTAI5tE1yMXCZAUG1HnHzva6
      keysecret: gLMxkMFHqYKMgplgUvTjBEoPWMQkED
      bucketname: sharechat
      filehost: media
