spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  data:
    cassandra:
      keyspace-name: scbase
      contact-points: 127.0.0.1
      port: 9042
      local-datacenter: datacenter1
      username: sharechat
      password: sharechat542
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sharechat?useUnicode=true&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: ecnu542_
server:
  port: 8888